import fs from 'fs';
import path from 'path';
import { runValidation } from '../core/validator.js';
import { openPullRequest } from '../core/pr-manager.js';

const TEMPLATE_FILES = {
  '.pdd/constitution.md': `# PDD Constitution

## 1. Change First
Every task is a change in an existing system.

## 2. Evidence Before Edit
Never change code without understanding current behavior.

## 3. Minimal Safe Delta
Prefer the smallest safe change.

## 4. Root Cause
Fix the cause, not the symptom.

## 5. Regression Awareness
Always consider what can break.

## 6. Reuse Patterns
Prefer existing patterns over new ones.

## 7. Verifiable Outcome
Every change must be validated.
`
};

function ensureDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeFileSafe(baseDir, relativePath, content, force = false) {
  const fullPath = path.join(baseDir, relativePath);
  if (!force && fs.existsSync(fullPath)) {
    return { path: relativePath, status: 'skipped' };
  }
  ensureDir(fullPath);
  fs.writeFileSync(fullPath, content, 'utf-8');
  return { path: relativePath, status: 'created' };
}

export async function runCli(argv = process.argv.slice(2)) {
  const command = argv[0];
  const force = argv.includes('--force');
  const cwd = process.cwd();

  // INIT
  if (command === 'init') {
    const results = Object.entries(TEMPLATE_FILES).map(([file, content]) =>
      writeFileSafe(cwd, file, content, force)
    );

    console.log('🚀 PDD initialized');
    for (const result of results) {
      console.log(`- ${result.status}: ${result.path}`);
    }
    return;
  }

  // FIX WORKFLOW (NO AI)
  if (command === 'fix') {
    const issue = argv
      .filter(arg => !arg.startsWith('--') && arg !== 'fix')
      .join(' ')
      .trim();

    const openPr = argv.includes('--open-pr');
    const dryRun = argv.includes('--dry-run');
    const noValidate = argv.includes('--no-validate');

    if (!issue) {
      console.error('❌ Missing issue description.');
      console.log('Use: pdd fix "description" [--open-pr] [--dry-run] [--no-validate]');
      process.exit(1);
    }

    console.log('🔧 PDD Fix Workflow');
    console.log(`Issue: ${issue}`);
    console.log(`Open PR: ${openPr ? 'yes' : 'no'}`);
    console.log(`Dry run: ${dryRun ? 'yes' : 'no'}`);
    console.log(`Validation: ${noValidate ? 'skipped' : 'enabled'}`);

    if (dryRun) {
      console.log('📝 Dry run only. No changes applied.');
      return;
    }

    console.log('🧩 Generating patch (placeholder)...');

    if (!noValidate) {
      runValidation();
    }

    if (openPr) {
      await openPullRequest({
        title: `fix: ${issue}`,
        body: `Automated fix generated by PDD for: ${issue}`
      });
    }

    console.log('✅ Fix workflow finished.');
    return;
  }

  // HELP
  if (command === 'help' || !command) {
    console.log('PDD CLI');
    console.log('');
    console.log('Commands:');
    console.log('  pdd init [--force]');
    console.log('  pdd fix "description" [--open-pr] [--dry-run] [--no-validate]');
    console.log('');
    return;
  }

  console.log(`Unknown command: ${command}`);
  console.log('Use: pdd help');
}
