blank_issues_enabled: false
contact_links:
  - name: "Questions and discussions"
    url: "https://github.com/pcoliveira90/pdd/discussions"
    about: "Use discussions for open questions and brainstorming."
